---
# SPDX-FileCopyrightText: Â© 2019 Clifford Weinmann <https://www.cliffordweinmann.com/>
# SPDX-License-Identifier: MIT-0

# Example Docker compose file

#-# Define the network
networks:
  mail-network:

#-# Define services
services:
  ## Mailcatcher, for testing email features (DEV ONLY)
  # This service is used in DEV only
  mailcatcher:
    image: ghcr.io/clifford2/mailcatcher:0.10.0-12.20251231
    networks:
      mail-network:
    ports:
      - "2525:2525"
      - "8080:8080"
    restart: on-failure
